### ISSUE TITLE
Unable to browse advise results

### ISSUE THREAD

**Issue by fridex** [Gkrumbach07/thoth-search#66]
**Describe the bug**

I'm unable to browse adviser results.

**To Reproduce**
1. Trigger `thamos advise`
2. Wait for the recommendations to be computed
3. Check the URL to Thoth Search reported - ex. https://thoth-station.ninja/search/adviser-220329062130-e66ea4b2a189ee44/summary
4. See an error

**Expected behavior**

Thoth Search UI should show results of the advise.

**Screenshots**

**Additional context**

**Comment by Gkrumbach07** [comment]
This is because that advise document does not include a lockfile as an input parameter. Usually the old pipfile is used to compare with the new pipfile. I believe the solution to this is to add a feature to select one or two environments to compare (or just one environment). This will allow for advises that dont have an input lockfile, and open up ways to compare environments across different operating systems or python versions.

I will prioritize this feature for the next sprint: https://github.com/thoth-station/search/issues/64

**Comment by fridex** [comment]
> This is because that advise document does not include a lockfile as an input parameter

The lock file is optional in inputt. The supplied lock file is used as a base for scoring dependencies that the user already uses. If the user does not have any lockfile yet (or she/he opts out from submitting it explicitly) we generate one for the user - https://thoth-station.ninja/j/user_stack

**Comment by Gkrumbach07** [comment]
fixed: see working link

https://thoth-station.ninja/search-stage/advise/adviser-220329062130-e66ea4b2a189ee44/summary
